-- 스키마 생성
CREATE SCHEMA WMS;
-- search_path 설정(이후 테이블 생성 시 스키마 생략 가능)
SET search_path TO WMS;

-- 사용자
CREATE TABLE TB_USER (
	USER_ID			VARCHAR(50)		NOT NULL,
	USER_NM			VARCHAR(200)	NOT NULL,
	PASSWORD		VARCHAR(200)	NOT NULL,
	ADMIN_YN		VARCHAR(1)		DEFAULT 'N'		NULL,
	USER_STS		VARCHAR(2)		DEFAULT '00'	NULL,
	USE_YN			VARCHAR(1)		DEFAULT 'Y'		NULL,
	ROLE			VARCHAR(200)	NULL,
	RMK				VARCHAR(500)	NULL,
	PROFILE_IMG_URL	TEXT			NULL,
	TEL1			VARCHAR(20)		NULL,
	TEL2			VARCHAR(20)		NULL,
	REG_ID			VARCHAR(50)		NULL,
	REG_DATE		TIMESTAMP		NULL,
	UPD_ID			VARCHAR(50)		NULL,
	UPD_DATE		TIMESTAMP		NULL
);

COMMENT ON TABLE TB_USER IS '사용자';
COMMENT ON COLUMN TB_USER.USER_ID IS '사용자ID';
COMMENT ON COLUMN TB_USER.USER_NM IS '사용자이름';
COMMENT ON COLUMN TB_USER.PASSWORD IS '비밀번호';
COMMENT ON COLUMN TB_USER.ADMIN_YN IS '관리자여부';
COMMENT ON COLUMN TB_USER.USER_STS IS '사용자상태';
COMMENT ON COLUMN TB_USER.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_USER.ROLE IS '권한ID';
COMMENT ON COLUMN TB_USER.RMK IS '비고';
COMMENT ON COLUMN TB_USER.PROFILE_IMG_URL IS '프로필 이미지';
COMMENT ON COLUMN TB_USER.TEL1 IS '연락처1';
COMMENT ON COLUMN TB_USER.TEL2 IS '연락처2';
COMMENT ON COLUMN TB_USER.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_USER.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_USER.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_USER.UPD_DATE IS '수정일자';

ALTER TABLE TB_USER ADD CONSTRAINT PK_TB_USER PRIMARY KEY (
	USER_ID
);

-- 사용자 로그
CREATE TABLE TB_USER_LOG (
	LOG_ID	VARCHAR(500)		NOT NULL,
	USER_ID	VARCHAR(50)		NOT NULL,
	PROG_ID	VARCHAR(20)		NULL,
	LOG_DTL	VARCHAR(500)		NULL,
	IP_ADDR	VARCHAR(30)		NULL,
	USER_AGENT	VARCHAR(100)		NULL,
	ACCESS_DATE	TIMESTAMP		NULL,
	REG_ID	VARCHAR(20)		NULL,
	REG_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_USER_LOG.LOG_ID IS '로그ID';
COMMENT ON COLUMN TB_USER_LOG.USER_ID IS '사용자ID';
COMMENT ON COLUMN TB_USER_LOG.PROG_ID IS '화면ID';
COMMENT ON COLUMN TB_USER_LOG.LOG_DTL IS '동작내용';
COMMENT ON COLUMN TB_USER_LOG.IP_ADDR IS 'IP주소';
COMMENT ON COLUMN TB_USER_LOG.USER_AGENT IS '사용자 에이전트';
COMMENT ON COLUMN TB_USER_LOG.ACCESS_DATE IS '접근일자';
COMMENT ON COLUMN TB_USER_LOG.REG_ID IS '생성자ID';
COMMENT ON COLUMN TB_USER_LOG.REG_DATE IS '생성일자';

ALTER TABLE TB_USER_LOG ADD CONSTRAINT PK_TB_USER_LOG PRIMARY KEY (
	LOG_ID
);

ALTER TABLE TB_USER_LOG ADD CONSTRAINT FK_TB_USER_TO_TB_USER_LOG FOREIGN KEY (
	USER_ID
)
REFERENCES TB_USER (
	USER_ID
);

-- 고객사
CREATE TABLE TB_SRVC (
	SRVC_CD	VARCHAR(4)		NOT NULL,
	SRVC_NM	VARCHAR(100)	NULL,
	REG_ID	VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID	VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_SRVC.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_SRVC.SRVC_NM IS '고객사명';
COMMENT ON COLUMN TB_SRVC.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_SRVC.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_SRVC.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_SRVC.UPD_DATE IS '수정일자';

ALTER TABLE TB_SRVC ADD CONSTRAINT PK_TB_SRVC PRIMARY KEY (
	SRVC_CD
);

-- 센터
CREATE TABLE TB_WH (
	WH_CD	VARCHAR(10)			NOT NULL,
	SRVC_CD	VARCHAR(4)		NOT NULL,
	WH_NM		VARCHAR(500)	NULL,
	DDGI_YN	VARCHAR(1)		NULL,
	USE_YN	VARCHAR(1)		NULL,
	RMK		VARCHAR(500)	NULL,
	REG_ID	VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID	VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_WH.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_WH.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_WH.WH_NM IS '센터명';
COMMENT ON COLUMN TB_WH.DDGI_YN IS '센터간이동여부';
COMMENT ON COLUMN TB_WH.USE_YN IS '센터사용여부';
COMMENT ON COLUMN TB_WH.RMK IS '비고';
COMMENT ON COLUMN TB_WH.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_WH.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_WH.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_WH.UPD_DATE IS '수정일자';

ALTER TABLE TB_WH ADD CONSTRAINT PK_TB_WH PRIMARY KEY (
	WH_CD,
	SRVC_CD
);

ALTER TABLE TB_WH ADD CONSTRAINT FK_TB_SRVC_TO_TB_WH_1 FOREIGN KEY (
	SRVC_CD
)
REFERENCES TB_SRVC (
	SRVC_CD
);

-- 사용자 권한센터
CREATE TABLE TB_USER_AUTH (
	USER_ID	VARCHAR(50)		NOT NULL,
	WH_CD	VARCHAR(10)		NOT NULL,
	SRVC_CD	VARCHAR(4)		NOT NULL,
	BASE_YN	VARCHAR(1)		NULL
);

COMMENT ON COLUMN TB_USER_AUTH.USER_ID IS '사용자ID';
COMMENT ON COLUMN TB_USER_AUTH.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_USER_AUTH.SRVC_CD IS '고객사ID';

ALTER TABLE TB_USER_AUTH ADD CONSTRAINT PK_TB_USER_AUTH PRIMARY KEY (
	USER_ID,
	WH_CD,
	SRVC_CD
);

ALTER TABLE TB_USER_AUTH ADD CONSTRAINT FK_TB_USER_TO_TB_USER_AUTH_1 FOREIGN KEY (
	USER_ID
)
REFERENCES TB_USER (
	USER_ID
);

ALTER TABLE TB_USER_AUTH ADD CONSTRAINT FK_TB_WH_TO_TB_USER_AUTH_1 FOREIGN KEY (
	WH_CD,
	SRVC_CD
)
REFERENCES TB_WH (
	WH_CD,
	SRVC_CD
);

-- 차량 마스터
CREATE TABLE TB_VEHICLE (
	VEHICLE_NO	VARCHAR(50)		NOT NULL,
	WH_CD	VARCHAR(10)		NOT NULL,
	SRVC_CD	VARCHAR(4)		NOT NULL,
	DRV_NM	VARCHAR(100)		NULL,
	HP_NO	VARCHAR(20)		NULL,
	TON_CLS_CD	VARCHAR(10)		NULL,
	USE_YN	VARCHAR(1)		NULL,
	REG_ID	VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID	VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_VEHICLE.VEHICLE_NO IS '차량번호';
COMMENT ON COLUMN TB_VEHICLE.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_VEHICLE.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_VEHICLE.DRV_NM IS '기사명';
COMMENT ON COLUMN TB_VEHICLE.HP_NO IS '휴대전화번호';
COMMENT ON COLUMN TB_VEHICLE.TON_CLS_CD IS '톤급';
COMMENT ON COLUMN TB_VEHICLE.USE_YN IS '차량사용여부';
COMMENT ON COLUMN TB_VEHICLE.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_VEHICLE.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_VEHICLE.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_VEHICLE.UPD_DATE IS '수정일자';

ALTER TABLE TB_VEHICLE ADD CONSTRAINT PK_TB_VEHICLE PRIMARY KEY (
	VEHICLE_NO
);

ALTER TABLE TB_VEHICLE ADD CONSTRAINT FK_TB_WH_TO_TB_VEHICLE_1 FOREIGN KEY (
    SRVC_CD,
	WH_CD
)
REFERENCES TB_WH (
    SRVC_CD,
	WH_CD
);

-- 거래처 마스터
CREATE TABLE TB_CLIENT (
	CLIENT_CD		VARCHAR(50)		NOT NULL,
	WH_CD			VARCHAR(10)		NOT NULL,
	SRVC_CD			VARCHAR(4)		NOT NULL,
	CLIENT_NM		VARCHAR(200)	NULL,
	BUSINESS_NO		VARCHAR(12)		NULL,
	BSN_TYPE_NM		VARCHAR(60)		NULL,
	BSN_ITEM_NM		VARCHAR(60)		NULL,
	PRESIDENT_NM	VARCHAR(50)		NULL,
	PRESIDENT_EMAIL	VARCHAR(50)		NULL,
	PRESIDENT_HP	VARCHAR(15)		NULL,
	ADDRESS			VARCHAR(1000)	NULL,
	NATION_CD		VARCHAR(3)		NULL,
	ZIP_CD			VARCHAR(10)		NULL,
	TEL_NO			VARCHAR(20)		NULL,
	TRADE_TYPE		VARCHAR(1)		NULL,
	USE_YN			VARCHAR(1)		NULL,
	REG_ID			VARCHAR(50)		NULL,
	REG_DATE		TIMESTAMP		NULL,
	UPD_ID			VARCHAR(50)		NULL,
	UPD_DATE		TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_CLIENT.CLIENT_CD IS '거래처코드';

COMMENT ON COLUMN TB_CLIENT.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_CLIENT.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_CLIENT.CLIENT_NM_KOR IS '거래처명';
COMMENT ON COLUMN TB_CLIENT.BUSINESS_NO IS '사업자번호';
COMMENT ON COLUMN TB_CLIENT.BSN_TYPE_NM IS '업태명';
COMMENT ON COLUMN TB_CLIENT.BSN_ITEM_NM IS '종목명';
COMMENT ON COLUMN TB_CLIENT.PRESIDENT_NM IS '대표자명';
COMMENT ON COLUMN TB_CLIENT.PRESIDENT_EMAIL IS '대표자_이메일주소';
COMMENT ON COLUMN TB_CLIENT.PRESIDENT_HP IS '대표자_H.P';
COMMENT ON COLUMN TB_CLIENT.ADDRESS IS '거래처주소';
COMMENT ON COLUMN TB_CLIENT.NATION_CD IS '국가코드';
COMMENT ON COLUMN TB_CLIENT.ZIP_CD IS '거래처우편번호';
COMMENT ON COLUMN TB_CLIENT.TEL_NO IS '거래처전화번호';
COMMENT ON COLUMN TB_CLIENT.TRADE_TYPE IS '거래유형(1 : 내수 : 2 : 수출 및 수입)';
COMMENT ON COLUMN TB_CLIENT.USE_YN IS '거래처 사용여부';
COMMENT ON COLUMN TB_CLIENT.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_CLIENT.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_CLIENT.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_CLIENT.UPD_DATE IS '수정일자';

ALTER TABLE TB_CLIENT ADD CONSTRAINT PK_TB_CLIENT PRIMARY KEY (
	CLIENT_CD
);

ALTER TABLE TB_CLIENT ADD CONSTRAINT FK_TB_WH_TO_TB_CLIENT FOREIGN KEY (
	SRVC_CD,
	WH_CD
)
REFERENCES TB_WH (
	SRVC_CD,
	WH_CD
);

-- 게시판
CREATE TABLE TB_BOARD (
	BOARD_ID		INTEGER  		NOT NULL,
	TITLE		VARCHAR(500),
	CONTENT		TEXT			NULL,
	VW_CNT		INTEGER			NULL,
	BOARD_TYPE	VARCHAR(2)		DEFAULT '00' NULL,
	USER_ID		VARCHAR(50)		NOT NULL,
	USE_YN		VARCHAR(1)		DEFAULT 'Y'	NULL,
	REG_ID		VARCHAR(50)		NULL,
	REG_DATE		TIMESTAMP		NULL,
	UPD_ID		VARCHAR(50)		NULL,
	UPD_DATE		TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_BOARD.BOARD_ID IS '게시판ID';
COMMENT ON COLUMN TB_BOARD.TITLE IS '제목';
COMMENT ON COLUMN TB_BOARD.CONTENT IS '내용';
COMMENT ON COLUMN TB_BOARD.VW_CNT IS '조회수';
COMMENT ON COLUMN TB_BOARD.BOARD_TYPE IS '게시분류(00 : 일반, 99 : 긴급)';
COMMENT ON COLUMN TB_BOARD.USER_ID IS '사용자ID';
COMMENT ON COLUMN TB_BOARD.USE_YN IS '게시여부';
COMMENT ON COLUMN TB_BOARD.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_BOARD.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_BOARD.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_BOARD.UPD_DATE IS '수정일자';

ALTER TABLE TB_BOARD ADD CONSTRAINT PK_TB_BOARD PRIMARY KEY (
	BOARD_ID
);

ALTER TABLE TB_BOARD ADD CONSTRAINT FK_TB_USER_TO_TB_BOARD FOREIGN KEY (
	USER_ID
)
REFERENCES TB_USER (
	USER_ID
);

-- 품번마스터
CREATE TABLE TB_ITEM (
	PROD_CD			VARCHAR(150)	NOT NULL,
	WH_CD			VARCHAR(10)		NOT NULL,
	SRVC_CD			VARCHAR(4)		NOT NULL,
	PROD_NM			VARCHAR(100)	NULL,
	STEITEM_NO		VARCHAR(150)	NULL,
	PROD_CATEGORY	VARCHAR(10)		NULL,
	PROD_SHAPE		VARCHAR(10)		NULL,
	PROD_TYPE		VARCHAR(30)		NULL,
	CREATE_TIME		TIMESTAMP		NULL,
	USE_YN			VARCHAR(1)		NULL,
	FIFO_YN			VARCHAR(1)		NULL,
	PRICE			NUMERIC(11, 2)	NULL,
	INNERPACK		NUMERIC(11, 2)	NULL,
	PROD_UNIT		VARCHAR(10)		NULL,
	WEIGHT			NUMERIC(11, 2)	NULL,
	REAL_WEIGHT		NUMERIC(11, 2)	NULL,
	WEIGHT_UNIT		VARCHAR(10)		NULL,
	PROD_SPEC		VARCHAR(100)	NULL,
	REG_ID			VARCHAR(50)		NULL,
	REG_DATE		TIMESTAMP		NULL,
	UPD_ID			VARCHAR(50)		NULL,
	UPD_DATE		TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_ITEM.PROD_CD IS '품목코드';
COMMENT ON COLUMN TB_ITEM.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_ITEM.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_ITEM.PROD_NM IS '품목명';
COMMENT ON COLUMN TB_ITEM.STEITEM_NO IS '설계품목코드(고객사품목코드)';
COMMENT ON COLUMN TB_ITEM.PROD_CATEGORY IS '품목구분';
COMMENT ON COLUMN TB_ITEM.PROD_SHAPE IS '품목형태';
COMMENT ON COLUMN TB_ITEM.PROD_TYPE IS '품목타입';
COMMENT ON COLUMN TB_ITEM.CREATE_TIME IS '생성일자';
COMMENT ON COLUMN TB_ITEM.USE_YN IS '품목 사용여부(Y/N)';
COMMENT ON COLUMN TB_ITEM.FIFO_YN IS '선입선출여부(Y/N)';
COMMENT ON COLUMN TB_ITEM.PRICE IS '단가';
COMMENT ON COLUMN TB_ITEM.INNERPACK IS '용기별 적입수량';
COMMENT ON COLUMN TB_ITEM.PROD_UNIT IS '품목단위';
COMMENT ON COLUMN TB_ITEM.WEIGHT IS '중량';
COMMENT ON COLUMN TB_ITEM.REAL_WEIGHT IS '실중량';
COMMENT ON COLUMN TB_ITEM.PROD_SPEC IS '품목사양';
COMMENT ON COLUMN TB_ITEM.WEIGHT_UNIT IS '무게단위';
COMMENT ON COLUMN TB_ITEM.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_ITEM.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_ITEM.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_ITEM.UPD_DATE IS '수정일자';

ALTER TABLE TB_ITEM ADD CONSTRAINT PK_TB_ITEM PRIMARY KEY (
	PROD_CD,
	WH_CD,
	SRVC_CD
);

ALTER TABLE TB_ITEM ADD CONSTRAINT FK_TB_WH_TO_TB_ITEM FOREIGN KEY (
	SRVC_CD,
	WH_CD
)
REFERENCES TB_WH (
	SRVC_CD,
	WH_CD
);

-- 존 마스터
CREATE TABLE TB_ZONE (
	ZONE_CD	VARCHAR(20)		NOT NULL,
	WH_CD	VARCHAR(10)		NOT NULL,
	SRVC_CD	VARCHAR(4)		NOT NULL,
	ZONE_NM	VARCHAR(30)		NULL,
	USE_YN	VARCHAR(1)	DEFAULT 'Y'	NULL,
	REG_ID	VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID	VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_ZONE.ZONE_CD IS '존ID';
COMMENT ON COLUMN TB_ZONE.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_ZONE.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_ZONE.ZONE_NM IS '존명';
COMMENT ON COLUMN TB_ZONE.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_ZONE.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_ZONE.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_ZONE.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_ZONE.UPD_DATE IS '수정일자';

ALTER TABLE TB_ZONE ADD CONSTRAINT PK_TB_ZONE PRIMARY KEY (
	ZONE_CD,
	WH_CD,
	SRVC_CD
);

ALTER TABLE TB_ZONE ADD CONSTRAINT FK_TB_WH_TO_TB_ZONE FOREIGN KEY (
	SRVC_CD,
	WH_CD
)
REFERENCES TB_WH (
	SRVC_CD,
	WH_CD
);

-- 로케이션 마스터
CREATE TABLE TB_LOC (
	LOC_CD	VARCHAR(50)		NOT NULL,
	ZONE_CD	VARCHAR(20)		NOT NULL,
	WH_CD	VARCHAR(10)		NOT NULL,
	SRVC_CD	VARCHAR(4)		NOT NULL,
	LOC_CLS_CD	VARCHAR(4)	DEFAULT '01'	NULL,
	USE_YN	VARCHAR(1)	DEFAULT 'Y'	NULL,
	RMK	VARCHAR(200)		NULL,
	REG_ID	VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID	VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_LOC.LOC_CD IS '로케이션ID';
COMMENT ON COLUMN TB_LOC.ZONE_CD IS '존ID';
COMMENT ON COLUMN TB_LOC.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_LOC.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_LOC.LOC_CLS_CD IS '로케이션종류(01 : 정상, 02 :불량, 03 : 스테이지';
COMMENT ON COLUMN TB_LOC.USE_YN IS '로케이션 사용여부';
COMMENT ON COLUMN TB_LOC.RMK IS '비고';
COMMENT ON COLUMN TB_LOC.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_LOC.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_LOC.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_LOC.UPD_DATE IS '수정일자';

ALTER TABLE TB_LOC ADD CONSTRAINT PK_TB_LOC PRIMARY KEY (
	LOC_CD,
	ZONE_CD,
	WH_CD,
	SRVC_CD
);

ALTER TABLE TB_LOC ADD CONSTRAINT FK_TB_ZONE_TO_TB_LOC FOREIGN KEY (
	ZONE_CD,
	SRVC_CD,
	WH_CD
)

REFERENCES TB_ZONE (
	ZONE_CD,
	SRVC_CD,
	WH_CD
);

-- 재고헤더
CREATE TABLE TB_STOCK_H (
	LOC_CD		VARCHAR(50)		NOT NULL,
	ZONE_CD		VARCHAR(20)		NOT NULL,
	WH_CD		VARCHAR(10)		NOT NULL,
	SRVC_CD		VARCHAR(4)		NOT NULL,
	PROD_CD		VARCHAR(120)	NOT NULL,
	STOCK_QTY	NUMERIC(12, 3)	NULL,
	ALLOC_QTY	NUMERIC(12, 3)	NULL,
	PICK_QTY	NUMERIC(12, 3)	NULL,
	REG_ID		VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID		VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_STOCK_H.LOC_CD IS '로케이션ID';
COMMENT ON COLUMN TB_STOCK_H.ZONE_CD IS '존ID';
COMMENT ON COLUMN TB_STOCK_H.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_STOCK_H.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_STOCK_H.PROD_CD IS '품목코드';
COMMENT ON COLUMN TB_STOCK_H.STOCK_QTY IS '재고수량';
COMMENT ON COLUMN TB_STOCK_H.ALLOC_QTY IS '할당수량';
COMMENT ON COLUMN TB_STOCK_H.PICK_QTY IS '피킹수량';
COMMENT ON COLUMN TB_STOCK_H.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_STOCK_H.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_STOCK_H.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_STOCK_H.UPD_DATE IS '수정일자';

ALTER TABLE TB_STOCK_H ADD CONSTRAINT PK_TB_STOCK_H PRIMARY KEY (
	LOC_CD,
	ZONE_CD,
	WH_CD,
	SRVC_CD,
	PROD_CD
);

ALTER TABLE TB_STOCK_H ADD CONSTRAINT FK_TB_LOC_TO_TB_STOCK_H FOREIGN KEY (
	ZONE_CD,
	LOC_CD,
	SRVC_CD,
	WH_CD
)
REFERENCES TB_LOC (
	ZONE_CD,
	LOC_CD,
	SRVC_CD,
	WH_CD
);

-- 재고상세
CREATE TABLE TB_STOCK_D (
	LOC_CD		VARCHAR(50)		NOT NULL,
	ZONE_CD		VARCHAR(20)		NOT NULL,
	WH_CD		VARCHAR(10)		NOT NULL,
	SRVC_CD		VARCHAR(4)		NOT NULL,
	PROD_CD		VARCHAR(120)	NOT NULL,
	LOT_NO		VARCHAR(20)		NOT NULL,
	STOCK_QTY	NUMERIC(12, 3)	NULL,
	ALLOC_QTY	NUMERIC(12, 3)	NULL,
	PICK_QTY	NUMERIC(12, 3)	NULL,
	PLT_ID		VARCHAR(20)		NULL,
	PLT_YN		VARCHAR(1)		DEFAULT 'N'	NULL,
	RMK			VARCHAR(1000)	NULL,
	PLT_QTY		NUMERIC(12, 3)	NULL,
	CARTON_QTY	NUMERIC(12, 3)	NULL,
	REG_ID		VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID		VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_STOCK_D.LOC_CD IS '로케이션ID';
COMMENT ON COLUMN TB_STOCK_D.ZONE_CD IS '존ID';
COMMENT ON COLUMN TB_STOCK_D.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_STOCK_D.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_STOCK_D.PROD_CD IS '품목코드';
COMMENT ON COLUMN TB_STOCK_D.LOT_NO IS 'LOT번호';
COMMENT ON COLUMN TB_STOCK_D.STOCK_QTY IS '재고수량';
COMMENT ON COLUMN TB_STOCK_D.ALLOC_QTY IS '할당수량';
COMMENT ON COLUMN TB_STOCK_D.PICK_QTY IS '피킹수량';
COMMENT ON COLUMN TB_STOCK_D.PLT_ID IS '파렛트ID';
COMMENT ON COLUMN TB_STOCK_D.PLT_YN IS '파렛트여부';
COMMENT ON COLUMN TB_STOCK_D.RMK IS '비고';
COMMENT ON COLUMN TB_STOCK_D.PLT_QTY IS '파렛트수량';
COMMENT ON COLUMN TB_STOCK_D.CARTON_QTY IS 'CARTON수량';
COMMENT ON COLUMN TB_STOCK_D.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_STOCK_D.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_STOCK_D.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_STOCK_D.UPD_DATE IS '수정일자';

ALTER TABLE TB_STOCK_D ADD CONSTRAINT PK_TB_STOCK_D PRIMARY KEY (
	ZONE_CD,
    LOC_CD,
	SRVC_CD,
	WH_CD,
	PROD_CD
);

ALTER TABLE TB_STOCK_D ADD CONSTRAINT FK_TB_STOCK_H_TO_TB_STOCK_D FOREIGN KEY (
	ZONE_CD,
    LOC_CD,
	SRVC_CD,
	WH_CD,
	PROD_CD
)
REFERENCES TB_STOCK_H (
	ZONE_CD,
    LOC_CD,
	SRVC_CD,
	WH_CD,
	PROD_CD
);

-- 트랜잭션
CREATE TABLE TB_ITRN (
	ITRN_KEY	VARCHAR(20)		NOT NULL,
	WH_CD	VARCHAR(10)		NOT NULL,
	SRVC_CD	VARCHAR(4)		NOT NULL,
	TRAN_TYPE	VARCHAR(2)		NULL,
	PROD_CD	VARCHAR(120)		NULL,
	LOT_NO	VARCHAR(8)		NULL,
	FROM_ZONE_CD	VARCHAR(20)		NULL,
	FROM_LOC_CD	VARCHAR(50)		NULL,
	FROM_ID	VARCHAR(100)		NULL,
	TO_ZONE_CD	VARCHAR(20)		NULL,
	TO_LOC_CD	VARCHAR(50)		NULL,
	TO_ID	VARCHAR(100)		NULL,
	SOURCE_KEY	VARCHAR(30)		NULL,
	QTY	NUMERIC(12, 3)		NULL,
	EFFECTIVE_DATE	VARCHAR(8)		NULL,
	VENDOR_CD	VARCHAR(20)		NULL,
	VENDOR_NM	VARCHAR(200)		NULL,
	RMK	VARCHAR(1000)		NULL,
	REG_ID	VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID	VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_ITRN.ITRN_KEY IS '트랜잭션KEY (시퀀스 번호로 채번 증가 진행)';
COMMENT ON COLUMN TB_ITRN.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_ITRN.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_ITRN.TRAN_TYPE IS '트랜잭션 타입 (DP : 입고, WD : 출고, MV :재고이동, AJ : 재고조정, TR : 물류이동)';
COMMENT ON COLUMN TB_ITRN.PROD_CD IS '품목번호';
COMMENT ON COLUMN TB_ITRN.LOT_NO IS 'LOT번호 (입고일자)';
COMMENT ON COLUMN TB_ITRN.FROM_ZONE_CD IS 'FROM  존ID';
COMMENT ON COLUMN TB_ITRN.FROM_LOC_CD IS 'FROM  로케이션ID';
COMMENT ON COLUMN TB_ITRN.FROM_ID IS 'FROM 시리얼 ID (BOX/PLT)';
COMMENT ON COLUMN TB_ITRN.TO_ZONE_CD IS 'TO 존ID';
COMMENT ON COLUMN TB_ITRN.TO_LOC_CD IS 'TO 로케이션ID';
COMMENT ON COLUMN TB_ITRN.TO_ID IS 'TO 시리얼 ID (BOX/PLT)';
COMMENT ON COLUMN TB_ITRN.SOURCE_KEY IS '지시번호';
COMMENT ON COLUMN TB_ITRN.QTY IS '작업수량';
COMMENT ON COLUMN TB_ITRN.EFFECTIVE_DATE IS '작업일자';
COMMENT ON COLUMN TB_ITRN.VENDOR_CD IS '거래처코드';
COMMENT ON COLUMN TB_ITRN.VENDOR_NM IS '거래처명';
COMMENT ON COLUMN TB_ITRN.RMK IS '비고';
COMMENT ON COLUMN TB_ITRN.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_ITRN.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_ITRN.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_ITRN.UPD_DATE IS '수정일자';

ALTER TABLE TB_ITRN ADD CONSTRAINT PK_TB_ITRN PRIMARY KEY (
	ITRN_KEY,
	WH_CD,
	SRVC_CD
);

ALTER TABLE TB_ITRN ADD CONSTRAINT FK_TB_WH_TO_TB_ITRN FOREIGN KEY (
	WH_CD,
	SRVC_CD
)
REFERENCES TB_WH (
	WH_CD,
	SRVC_CD
);

-- 입고헤더
CREATE TABLE TB_RECEIPT_H (
	IN_NO	VARCHAR(30)		NOT NULL,
	WH_CD	VARCHAR(10)		NOT NULL,
	SRVC_CD	VARCHAR(4)		NOT NULL,
	IN_EXPECTED_DATE	VARCHAR(8)		NOT NULL,
	IN_EXPECTED_NO	VARCHAR(20)		NOT NULL,
	VENDOR_CD	VARCHAR(20)		NULL,
	RECEIPT_CLS_CD	VARCHAR(2)		NULL,
	VENDOR_NM	VARCHAR(50)		NULL,
	TOT_PLT_QTY	NUMERIC(12, 3)		NULL,
	ORIGINAL_QTY	NUMERIC(12, 3)		NULL,
	EXPECTED_QTY	NUMERIC(12, 3)		NULL,
	OPEN_QTY	NUMERIC(12, 3)		NULL,
	RECEIVED_QTY	NUMERIC(12, 3)		NULL,
	STATUS	VARCHAR(2)	DEFAULT '00'	NULL,
	RMK	VARCHAR(1000)		NULL,
	RECEIPT_DATE	TIMESTAMP		NULL,
	RECEIPT_NO	NUMERIC(12, 3)		NULL,
	IN_V_NO	VARCHAR(60)		NULL,
	IN_V_ID	VARCHAR(30)		NULL,
	IN_V_NM	VARCHAR(50)		NULL,
	VENDOR_ADDRESS	VARCHAR(1000)		NULL,
	RECEIPT_TYPE	VARCHAR(30)		NULL,
	ZIP_CD	VARCHAR(10)		NULL,
	TEL_NO	VARCHAR(20)		NULL,
	MANAGER_NM	VARCHAR(50)		NULL,
	REG_ID	VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID	VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_RECEIPT_H.IN_NO IS '입고지시번호';
COMMENT ON COLUMN TB_RECEIPT_H.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_RECEIPT_H.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_RECEIPT_H.IN_EXPECTED_DATE IS '입고에정일자';
COMMENT ON COLUMN TB_RECEIPT_H.IN_EXPECTED_NO IS '입고예정번호';
COMMENT ON COLUMN TB_RECEIPT_H.VENDOR_CD IS '입고거래처코드';
COMMENT ON COLUMN TB_RECEIPT_H.RECEIPT_CLS_CD IS '입고구분(01 : 정상, 99 : 불량)';
COMMENT ON COLUMN TB_RECEIPT_H.VENDOR_NM IS '입고거래처명';
COMMENT ON COLUMN TB_RECEIPT_H.TOT_PLT_QTY IS '총좌수';
COMMENT ON COLUMN TB_RECEIPT_H.ORIGINAL_QTY IS '원입고예정량';
COMMENT ON COLUMN TB_RECEIPT_H.EXPECTED_QTY IS '입고예정량';
COMMENT ON COLUMN TB_RECEIPT_H.OPEN_QTY IS '입고작업량';
COMMENT ON COLUMN TB_RECEIPT_H.RECEIVED_QTY IS '입고확정량';
COMMENT ON COLUMN TB_RECEIPT_H.STATUS IS '입고상태(00 : 입고예정, 01 : 부분입고, 09 : 입고완료)';
COMMENT ON COLUMN TB_RECEIPT_H.RMK IS '비고';
COMMENT ON COLUMN TB_RECEIPT_H.RECEIPT_DATE IS '입고확정일자';
COMMENT ON COLUMN TB_RECEIPT_H.RECEIPT_NO IS '입고확정번호';
COMMENT ON COLUMN TB_RECEIPT_H.IN_V_NO IS '차량번호';
COMMENT ON COLUMN TB_RECEIPT_H.IN_V_ID IS '기사ID';
COMMENT ON COLUMN TB_RECEIPT_H.IN_V_NM IS '기사성명';
COMMENT ON COLUMN TB_RECEIPT_H.VENDOR_ADDRESS IS '입고처 주소';
COMMENT ON COLUMN TB_RECEIPT_H.RECEIPT_TYPE IS '입고타입';
COMMENT ON COLUMN TB_RECEIPT_H.ZIP_CD IS '우편번호';
COMMENT ON COLUMN TB_RECEIPT_H.TEL_NO IS '연락처';
COMMENT ON COLUMN TB_RECEIPT_H.MANAGER_NM IS '담당자명';
COMMENT ON COLUMN TB_RECEIPT_H.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_RECEIPT_H.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_RECEIPT_H.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_RECEIPT_H.UPD_DATE IS '수정일자';

ALTER TABLE TB_RECEIPT_H ADD CONSTRAINT PK_TB_RECEIPT_H PRIMARY KEY (
	IN_NO,
	WH_CD,
	SRVC_CD
);

ALTER TABLE TB_RECEIPT_H ADD CONSTRAINT FK_TB_WH_TO_TB_RECEIPT_H FOREIGN KEY (
	SRVC_CD,
	WH_CD
)
REFERENCES TB_WH (
	SRVC_CD,
	WH_CD
);

-- 입고상세
CREATE TABLE TB_RECEIPT_D (
	IN_EXPECTED_SEQ	NUMERIC(12, 3)		NOT NULL,
	IN_NO	VARCHAR(30)		NOT NULL,
	WH_CD	VARCHAR(10)		NOT NULL,
	SRVC_CD	VARCHAR(4)		NOT NULL,
	IN_EXPECTED_DATE	VARCHAR(8)		NULL,
	IN_EXPECTED_NO	VARCHAR(20)		NULL,
	VENDOR_CD	VARCHAR(20)		NULL,
	VENDOR_NM	VARCHAR(200)		NULL,
	PROD_CD	VARCHAR(120)		NULL,
	ORIGINAL_QTY	NUMERIC(12, 3)		NULL,
	EXPECTED_QTY	NUMERIC(12, 3)		NULL,
	OPEN_QTY	NUMERIC(12, 3)		NULL,
	TEMP_QTY	NUMERIC(12, 3)		NULL,
	RECEIVED_QTY	NUMERIC(12, 3)		NULL,
	STATUS	VARCHAR(2)	DEFAULT '00'	NULL,
	RMK	VARCHAR(1000)		NULL,
	IN_ZONE_CD	VARCHAR(20)		NULL,
	IN_LOC_CD	VARCHAR(20)		NULL,
	NOT_RSN_CD	VARCHAR(4)		NULL,
	LOT_NO	VARCHAR(8)		NULL,
	RECEIPT_DATE	TIMESTAMP		NULL,
	RECEIPT_NO	NUMERIC(12, 3)		NULL,
	RECEIPT_SEQ	NUMERIC(12, 3)		NULL,
	PDA_YN	VARCHAR(1)	DEFAULT 'N'	NULL,
	PDA_SCAN_CNT	NUMERIC(12, 3)		NULL,
	PDA_SCAN_QTY	NUMERIC(12, 3)		NULL,
	WEIGHT	NUMERIC(12, 3)		NULL,
	PLT_QTY	NUMERIC(12, 3)		NULL,
	CARTON_QTY	NUMERIC(12, 3)		NULL,
	ITEM_FLAG	VARCHAR(10)		NULL,
	REG_ID	VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID	VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_RECEIPT_D.IN_EXPECTED_SEQ IS '입고예정순번';
COMMENT ON COLUMN TB_RECEIPT_D.IN_NO IS '입고지시번호';
COMMENT ON COLUMN TB_RECEIPT_D.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_RECEIPT_D.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_RECEIPT_D.IN_EXPECTED_DATE IS '입고에정일자';
COMMENT ON COLUMN TB_RECEIPT_D.IN_EXPECTED_NO IS '입고예정번호';
COMMENT ON COLUMN TB_RECEIPT_D.VENDOR_CD IS '입고처코드';
COMMENT ON COLUMN TB_RECEIPT_D.VENDOR_NM IS '입고거래처명';
COMMENT ON COLUMN TB_RECEIPT_D.PROD_CD IS '품번';
COMMENT ON COLUMN TB_RECEIPT_D.ORIGINAL_QTY IS '원입고예정량';
COMMENT ON COLUMN TB_RECEIPT_D.EXPECTED_QTY IS '입고예정량';
COMMENT ON COLUMN TB_RECEIPT_D.OPEN_QTY IS '입고작업량';
COMMENT ON COLUMN TB_RECEIPT_D.TEMP_QTY IS '가입고량';
COMMENT ON COLUMN TB_RECEIPT_D.RECEIVED_QTY IS '입고확정량';
COMMENT ON COLUMN TB_RECEIPT_D.STATUS IS '입고상태(00 : 입고예정, 01 : 부분입고, 09 : 입고완료)';
COMMENT ON COLUMN TB_RECEIPT_D.RMK IS '비고';
COMMENT ON COLUMN TB_RECEIPT_D.IN_ZONE_CD IS '입고 존코드';
COMMENT ON COLUMN TB_RECEIPT_D.IN_LOC_CD IS '기본 적치 로케이션';
COMMENT ON COLUMN TB_RECEIPT_D.NOT_RSN_CD IS '미입고 사유 코드';
COMMENT ON COLUMN TB_RECEIPT_D.LOT_NO IS '로트번호(입고일자)';
COMMENT ON COLUMN TB_RECEIPT_D.RECEIVE_DATE IS '입고확정일자';
COMMENT ON COLUMN TB_RECEIPT_D.RECEIVE_NO IS '입고확정번호';
COMMENT ON COLUMN TB_RECEIPT_D.RECEIVE_SEQ IS '입고확정순번';
COMMENT ON COLUMN TB_RECEIPT_D.PDA_YN IS 'PDA 작업여부';
COMMENT ON COLUMN TB_RECEIPT_D.PDA_SCAN_CNT IS 'PDA스캔건수';
COMMENT ON COLUMN TB_RECEIPT_D.PDA_SCAN_QTY IS 'PDA스캔수량';
COMMENT ON COLUMN TB_RECEIPT_D.WEIGHT IS '중량';
COMMENT ON COLUMN TB_RECEIPT_D.PLT_QTY IS 'PLT수량';
COMMENT ON COLUMN TB_RECEIPT_D.CARTON_QTY IS 'CARTON수량';
COMMENT ON COLUMN TB_RECEIPT_D.ITEM_FLAG IS '품목구분';
COMMENT ON COLUMN TB_RECEIPT_D.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_RECEIPT_D.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_RECEIPT_D.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_RECEIPT_D.UPD_DATE IS '수정일자';

ALTER TABLE TB_RECEIPT_D ADD CONSTRAINT PK_TB_RECEIPT_D PRIMARY KEY (
	IN_EXPECTED_SEQ,
	IN_NO,
	WH_CD,
	SRVC_CD
);

ALTER TABLE TB_RECEIPT_D ADD CONSTRAINT FK_TB_RECEIPT_H_TO_TB_RECEIPT_D FOREIGN KEY (
	SRVC_CD,
	WH_CD,
	IN_NO
)
REFERENCES TB_RECEIPT_H (
	SRVC_CD,
	WH_CD,
	IN_NO
);

-- 출고헤더
CREATE TABLE TB_ORDER_H (
	OUT_NO	VARCHAR(30)		NOT NULL,
	WH_CD	VARCHAR(10)		NOT NULL,
	SRVC_CD	VARCHAR(4)		NOT NULL,
	OUT_EXPECTED_DATE	VARCHAR(8)		NOT NULL,
	OUT_ASN_NO	VARCHAR(20)		NOT NULL,
	ORDER_TYPE	VARCHAR(30)		NULL,
	STATUS	VARCHAR(2)	DEFAULT '00'	NULL,
	TOT_PLT_QTY	NUMERIC(12, 3)		NULL,
	ORIGINAL_QTY	NUMERIC(12, 3)		NULL,
	INTEND_QTY	NUMERIC(12, 3)		NULL,
	OPEN_QTY	NUMERIC(12, 3)		NULL,
	ALLOC_QTY	NUMERIC(12, 3)		NULL,
	PICK_QTY	NUMERIC(12, 3)		NULL,
	OUT_QTY	NUMERIC(12, 3)		NULL,
	RMK	VARCHAR(1000)		NULL,
	CONFIRM_DATE	VARCHAR(8)		NULL,
	CONFIRM_NO	NUMERIC(12, 3)		NULL,
	OUT_V_NO	VARCHAR(60)		NULL,
	OUT_V_ID	VARCHAR(30)		NULL,
	OUT_V_NM	VARCHAR(50)		NULL,
	REG_ID	VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID	VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_ORDER_H.OUT_NO IS '출고지시번호';
COMMENT ON COLUMN TB_ORDER_H.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_ORDER_H.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_ORDER_H.OUT_EXPECTED_DATE IS '출고예정일자';
COMMENT ON COLUMN TB_ORDER_H.OUT_ASN_NO IS '촐고예정번호';
COMMENT ON COLUMN TB_ORDER_H.ORDER_TYPE IS '출고타입';
COMMENT ON COLUMN TB_ORDER_H.STATUS IS '출고상태 (00: 미작업, 01 : 부분할당, 02 : 할당완료, 03 : 작업생성완료, 04 : 부분피킹,  05 : 피킹완료, 09 : 출고완료)';
COMMENT ON COLUMN TB_ORDER_H.TOT_PLT_QTY IS '총좌수';
COMMENT ON COLUMN TB_ORDER_H.ORIGINAL_QTY IS '원출고예정량';
COMMENT ON COLUMN TB_ORDER_H.INTEND_QTY IS '출고예정량';
COMMENT ON COLUMN TB_ORDER_H.OPEN_QTY IS '출고작업량';
COMMENT ON COLUMN TB_ORDER_H.ALLOC_QTY IS '출고할당량';
COMMENT ON COLUMN TB_ORDER_H.PICK_QTY IS '출고피킹량';
COMMENT ON COLUMN TB_ORDER_H.OUT_QTY IS '출고확정량';
COMMENT ON COLUMN TB_ORDER_H.RMK IS '비고';
COMMENT ON COLUMN TB_ORDER_H.CONFIRM_DATE IS '출고확정일자';
COMMENT ON COLUMN TB_ORDER_H.CONFIRM_NO IS '출고확정번호';
COMMENT ON COLUMN TB_ORDER_H.OUT_V_NO IS '차량번호';
COMMENT ON COLUMN TB_ORDER_H.OUT_V_ID IS '기사ID';
COMMENT ON COLUMN TB_ORDER_H.OUT_V_NM IS '기사성명';
COMMENT ON COLUMN TB_ORDER_H.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_ORDER_H.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_ORDER_H.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_ORDER_H.UPD_DATE IS '수정일자';

ALTER TABLE TB_ORDER_H ADD CONSTRAINT PK_TB_ORDER_H PRIMARY KEY (
	OUT_NO,
	WH_CD,
	SRVC_CD
);

ALTER TABLE TB_ORDER_H ADD CONSTRAINT FK_TB_WH_TO_TB_ORDER_H FOREIGN KEY (
	SRVC_CD,
	WH_CD
)

REFERENCES TB_WH (
	SRVC_CD,
	WH_CD
);

-- 출고상세
CREATE TABLE TB_ORDER_D (
	OUT_EXPECTED_SEQ	NUMERIC(12, 3)		NOT NULL,
	OUT_NO	VARCHAR(30)		NOT NULL,
	WH_CD	VARCHAR(10)		NOT NULL,
	SRVC_CD	VARCHAR(4)		NOT NULL,
	OUT_ORD_CLS_CD	VARCHAR(1)		NULL,
	OUT_EXPECTED_DATE	VARCHAR(8)		NOT NULL,
	OUT_ASN_NO	VARCHAR(20)		NOT NULL,
	STATUS	VARCHAR(2)	DEFAULT '00'	NULL,
	PROD_CD	VARCHAR(120)		NULL,
	ORIGINAL_QTY	NUMERIC(12, 3)		NULL,
	INTEND_QTY	NUMERIC(12, 3)		NULL,
	OPEN_QTY	NUMERIC(12, 3)		NULL,
	ALLOC_QTY	NUMERIC(12, 3)		NULL,
	PICK_QTY	NUMERIC(12, 3)		NULL,
	OUT_QTY	NUMERIC(12, 3)		NULL,
	CONFIRM_DATE	VARCHAR(8)		NULL,
	CONFIRM_NO	NUMERIC(12, 3)		NULL,
	CONFIRM_SEQ	NUMERIC(12, 3)		NULL,
	NON_INSHP_CD	VARCHAR(2)		NULL,
	RMK	VARCHAR(1000)		NULL,
	BARCODE	VARCHAR(100)		NULL,
	PLT_YN	VARCHAR(1)	DEFAULT 'N'	NULL,
	WEIGHT	NUMERIC(12, 3)		NULL,
	PLT_QTY	NUMERIC(12, 3)		NULL,
	CARBON_QTY	NUMERIC(12, 3)		NULL,
	VENDOR_CD	VARCHAR(20)		NULL,
	VENDOR_NM	VARCHAR(200)		NULL,
	VENDOR_ADDRESS	VARCHAR(1000)		NULL,
	VENDOR_BUS_RNO	VARCHAR(20)		NULL,
	ZIP_CD	VARCHAR(10)		NULL,
	TEL_NO	VARCHAR(20)		NULL,
	ITEM_FLAG	VARCHAR(10)		NULL,
	MANAGER_NM	VARCHAR(50)		NULL,
	REG_ID	VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID	VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_ORDER_D.OUT_EXPECTED_SEQ IS '촐고예정순번';
COMMENT ON COLUMN TB_ORDER_D.OUT_NO IS '출고지시번호';
COMMENT ON COLUMN TB_ORDER_D.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_ORDER_D.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_ORDER_D.OUT_ORD_CLS_CD IS '출고지시구분(1 : 제품출고,  2: 사급출고, 3: 반품출고)';
COMMENT ON COLUMN TB_ORDER_D.OUT_EXPECTED_DATE IS '출고예정일자';
COMMENT ON COLUMN TB_ORDER_D.OUT_ASN_NO IS '촐고예정번호';
COMMENT ON COLUMN TB_ORDER_D.STATUS IS '출고상태 (00 : 미작업, 09 : 출고완료)';
COMMENT ON COLUMN TB_ORDER_D.PROD_CD IS '품목번호';
COMMENT ON COLUMN TB_ORDER_D.ORIGINAL_QTY IS '원출고예정량';
COMMENT ON COLUMN TB_ORDER_D.INTEND_QTY IS '출고예정량';
COMMENT ON COLUMN TB_ORDER_D.OPEN_QTY IS '출고작업량';
COMMENT ON COLUMN TB_ORDER_D.ALLOC_QTY IS '출고할당량';
COMMENT ON COLUMN TB_ORDER_D.PICK_QTY IS '출고피킹량';
COMMENT ON COLUMN TB_ORDER_D.OUT_QTY IS '출고확정량';
COMMENT ON COLUMN TB_ORDER_D.CONFIRM_DATE IS '출고확정일자';
COMMENT ON COLUMN TB_ORDER_D.CONFIRM_NO IS '출고확정번호';
COMMENT ON COLUMN TB_ORDER_D.CONFIRM_SEQ IS '출고확정순번';
COMMENT ON COLUMN TB_ORDER_D.NON_INSHP_CD IS '결품(부분출고)사유';
COMMENT ON COLUMN TB_ORDER_D.RMK IS '비고';
COMMENT ON COLUMN TB_ORDER_D.BARCODE IS '바코드';
COMMENT ON COLUMN TB_ORDER_D.PLT_YN IS '파렛트구분(Y/N)';
COMMENT ON COLUMN TB_ORDER_D.WEIGHT IS '중량';
COMMENT ON COLUMN TB_ORDER_D.PLT_QTY IS '파렛트수량';
COMMENT ON COLUMN TB_ORDER_D.CARBON_QTY IS 'CARBON수량';
COMMENT ON COLUMN TB_ORDER_D.VENDOR_CD IS '출고거래처코드';
COMMENT ON COLUMN TB_ORDER_D.VENDOR_NM IS '출고거래처명';
COMMENT ON COLUMN TB_ORDER_D.VENDOR_ADDRESS IS '출고거래처주소';
COMMENT ON COLUMN TB_ORDER_D.VENDOR_BUS_RNO IS '출고거래처사업자번호';
COMMENT ON COLUMN TB_ORDER_D.ZIP_CD IS '우편번호';
COMMENT ON COLUMN TB_ORDER_D.TEL_NO IS '연락처';
COMMENT ON COLUMN TB_ORDER_D.ITEM_FLAG IS '품목구분';
COMMENT ON COLUMN TB_ORDER_D.MANAGER_NM IS '출고거래처담당자명';
COMMENT ON COLUMN TB_ORDER_D.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_ORDER_D.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_ORDER_D.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_ORDER_D.UPD_DATE IS '수정일자';

ALTER TABLE TB_ORDER_D ADD CONSTRAINT PK_TB_ORDER_D PRIMARY KEY (
	OUT_EXPECTED_SEQ,
	OUT_NO,
	WH_CD,
	SRVC_CD
);

ALTER TABLE TB_ORDER_D ADD CONSTRAINT FK_TB_ORDER_H_TO_TB_ORDER_D FOREIGN KEY (
	SRVC_CD,
	WH_CD,
	OUT_NO
)
REFERENCES TB_ORDER_H (
	SRVC_CD,
	WH_CD,
	OUT_NO
);

-- 출고할당/피킹관리
CREATE TABLE TB_ORDER_ALLOC (
	PICK_NO	VARCHAR(30)		NOT NULL,
	OUT_EXPECTED_SEQ	NUMERIC(12, 3)		NOT NULL,
	OUT_NO	VARCHAR(30)		NOT NULL,
	WH_CD	VARCHAR(10)		NOT NULL,
	SRVC_CD	VARCHAR(4)		NOT NULL,
	OUT_ZONE_CD	VARCHAR(20)		NOT NULL,
	OUT_LOC_CD	VARCHAR(50)		NOT NULL,
	LOT_NO	VARCHAR(20)		NULL,
	PROD_CD	VARCHAR(120)		NULL,
	OPEN_QTY	NUMERIC(12, 3)		NULL,
	OUT_QTY	NUMERIC(12, 3)		NULL,
	STATUS	VARCHAR(2)	DEFAULT '00'	NULL,
	PDA_YN	VARCHAR(1)	DEFAULT 'N'	NULL,
	LOAD_YN	VARCHAR(1)	DEFAULT 'N'	NULL,
	PLT_YN	VARCHAR(1)	DEFAULT 'N'	NULL,
	RMK	VARCHAR(1000)		NULL,
	PDA_SCAN_CNT	NUMERIC(12, 3)		NULL,
	PDA_SCAN_QTY	NUMERIC(12, 3)		NULL,
	MANUAL_ALLOC_YN	VARCHAR(1)	DEFAULT 'N'	NULL,
	VEHICLE_NO	VARCHAR(60)		NULL,
	REG_ID	VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID	VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_ORDER_ALLOC.PICK_NO IS '출고피킹번호';
COMMENT ON COLUMN TB_ORDER_ALLOC.OUT_EXPECTED_SEQ IS '촐고예정순번';
COMMENT ON COLUMN TB_ORDER_ALLOC.OUT_NO IS '출고지시번호';
COMMENT ON COLUMN TB_ORDER_ALLOC.WH_CD IS '센터ID';
COMMENT ON COLUMN TB_ORDER_ALLOC.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_ORDER_ALLOC.OUT_ZONE_CD IS '출고 존ID';
COMMENT ON COLUMN TB_ORDER_ALLOC.OUT_LOC_CD IS '출고 로케이션ID';
COMMENT ON COLUMN TB_ORDER_ALLOC.LOT_NO IS '출고 LOT번호(출고일자)';
COMMENT ON COLUMN TB_ORDER_ALLOC.PROD_CD IS '품목번호';
COMMENT ON COLUMN TB_ORDER_ALLOC.OPEN_QTY IS '작업량';
COMMENT ON COLUMN TB_ORDER_ALLOC.OUT_QTY IS '출고수량';
COMMENT ON COLUMN TB_ORDER_ALLOC.STATUS IS '출고상태(00: 미작업, 05 : 피캉완료, 09 : 출고완료)';
COMMENT ON COLUMN TB_ORDER_ALLOC.PDA_YN IS 'PDA 작업여부(Y/N)';
COMMENT ON COLUMN TB_ORDER_ALLOC.LOAD_YN IS '상차유무';
COMMENT ON COLUMN TB_ORDER_ALLOC.PLT_YN IS '파렛트 여부(Y/N)';
COMMENT ON COLUMN TB_ORDER_ALLOC.RMK IS '비고';
COMMENT ON COLUMN TB_ORDER_ALLOC.PDA_SCAN_CNT IS 'PDA 스캔 건수';
COMMENT ON COLUMN TB_ORDER_ALLOC.PDA_SCAN_QTY IS 'PDA 스캔 수량';
COMMENT ON COLUMN TB_ORDER_ALLOC.MANUAL_ALLOC_YN IS '수동할당여부(Y/N)';
COMMENT ON COLUMN TB_ORDER_ALLOC.VEHICLE_NO IS '차량번호';
COMMENT ON COLUMN TB_ORDER_ALLOC.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_ORDER_ALLOC.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_ORDER_ALLOC.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_ORDER_ALLOC.UPD_DATE IS '수정일자';

ALTER TABLE TB_ORDER_ALLOC ADD CONSTRAINT PK_TB_ORDER_ALLOC PRIMARY KEY (
	PICK_NO,
	OUT_EXPECTED_SEQ,
	OUT_NO,
	WH_CD,
	SRVC_CD
);

ALTER TABLE TB_ORDER_ALLOC ADD CONSTRAINT FK_TB_ORDER_D_TO_TB_ORDER_ALLOC FOREIGN KEY (
	SRVC_CD,
	WH_CD,
	OUT_NO,
	OUT_EXPECTED_SEQ
)
REFERENCES TB_ORDER_D (
	SRVC_CD,
	WH_CD,
	OUT_NO,
	OUT_EXPECTED_SEQ
);

-- 게시판 첨부파일 관리
CREATE TABLE WMS.TB_COMM_BOARD_FILE (
	FILE_ID		INTEGER			NOT NULL,
	BOARD_ID	INTEGER			NOT NULL,
	REF_TYPE	VARCHAR(10)		NOT NULL,
	FILE_NM		VARCHAR(500)	NULL,
	FILE_SIZE	VARCHAR(50)		NULL,
	FILE_PATH	VARCHAR(1000)	NULL,
	REG_ID		VARCHAR(50)		NULL,
	REG_DATE	TIMESTAMP		NULL,
	UPD_ID		VARCHAR(50)		NULL,
	UPD_DATE	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_COMM_BOARD_FILE.FILE_ID IS '파일ID';
COMMENT ON COLUMN TB_COMM_BOARD_FILE.BOARD_ID IS '게시판ID';
COMMENT ON COLUMN TB_COMM_BOARD_FILE.REF_TYPE IS '첨부타입';
COMMENT ON COLUMN TB_COMM_BOARD_FILE.FILE_NM IS '파일명';
COMMENT ON COLUMN TB_COMM_BOARD_FILE.FILE_SIZE IS '파일크기';
COMMENT ON COLUMN TB_COMM_BOARD_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TB_COMM_BOARD_FILE.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_COMM_BOARD_FILE.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_COMM_BOARD_FILE.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_COMM_BOARD_FILE.UPD_DATE IS '수정일자';

ALTER TABLE TB_COMM_BOARD_FILE ADD CONSTRAINT PK_TB_COMM_BOARD_FILE PRIMARY KEY (
	FILE_ID
);

ALTER TABLE TB_COMM_BOARD_FILE ADD CONSTRAINT FK_TB_BOARD_TO_TB_COMM_BOARD_FILE FOREIGN KEY (
	BOARD_ID
)
REFERENCES TB_BOARD (
	BOARD_ID
);

-- 공통 코드 테이블
CREATE TABLE TB_COMM_CODE (
	SYS_MD_CD		VARCHAR(2)			NOT NULL,
	SYS_GRP_CD		VARCHAR(10)			NOT NULL,
	SYS_CD			VARCHAR(10)			NOT NULL,
	SYS_GRP_CDNM	VARCHAR(200)			NULL,
	SYS_CDNM		VARCHAR(200)			NULL,
	SYS_DESC		VARCHAR(200)			NULL,
	USE_YN			VARCHAR(1)	DEFAULT 'Y'	NULL,
	SYS_ETC1		VARCHAR(50)				NULL,
	SYS_ETC2		VARCHAR(50)				NULL,
	SYS_ETC3		VARCHAR(50)				NULL,
	SYS_ETC4		VARCHAR(50)				NULL,
	SYS_ETC5		VARCHAR(50)				NULL,
	SRVC_CD			VARCHAR(4)			NOT NULL,
	SYS_SORT_SEQ	INTEGER					NULL,
	REG_ID			VARCHAR(50)				NULL,
	REG_DATE		TIMESTAMP				NULL,
	UPD_ID			VARCHAR(50)				NULL,
	UPD_DATE		TIMESTAMP				NULL
);

COMMENT ON COLUMN TB_COMM_CODE.SYS_MD_CD IS '모듈코드';
COMMENT ON COLUMN TB_COMM_CODE.SYS_MC_CD IS '대분류코드';
COMMENT ON COLUMN TB_COMM_CODE.SYS_CD IS '소분류코드';
COMMENT ON COLUMN TB_COMM_CODE.SYS_MC_CDNM IS '대분류코드명';
COMMENT ON COLUMN TB_COMM_CODE.SYS_CDNM IS '소분류코드명';
COMMENT ON COLUMN TB_COMM_CODE.SYS_DESC IS '코드설명';
COMMENT ON COLUMN TB_COMM_CODE.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_COMM_CODE.SYS_ETC1 IS '코드확장내용_1';
COMMENT ON COLUMN TB_COMM_CODE.SYS_ETC2 IS '코드확장내용_2';
COMMENT ON COLUMN TB_COMM_CODE.SYS_ETC3 IS '코드확장내용_3';
COMMENT ON COLUMN TB_COMM_CODE.SYS_ETC4 IS '코드확장내용_4';
COMMENT ON COLUMN TB_COMM_CODE.SYS_ETC5 IS '코드확장내용_5';
COMMENT ON COLUMN TB_COMM_CODE.SRVC_CD IS '고객사ID';
COMMENT ON COLUMN TB_COMM_CODE.SYS_SORT_SEQ IS '코드순번';
COMMENT ON COLUMN TB_COMM_CODE.REG_ID IS '등록자ID';
COMMENT ON COLUMN TB_COMM_CODE.REG_DATE IS '등록일자';
COMMENT ON COLUMN TB_COMM_CODE.UPD_ID IS '수정자ID';
COMMENT ON COLUMN TB_COMM_CODE.UPD_DATE IS '수정일자';

ALTER TABLE TB_COMM_CODE ADD CONSTRAINT PK_TB_COMM_CODE PRIMARY KEY (
	SYS_MD_CD,
	SYS_MC_CD,
	SYS_CD
);

-- 프로시저 로그
CREATE TABLE TB_PROC_LOG (
	PROC_NM			VARCHAR(200)		NULL,
	EXEC_START_DATE	TIMESTAMP			NULL,
	EXEC_PARAM		VARCHAR(500)		NULL,
	RESULT_MSG		VARCHAR(1000)		NULL,
	EXEC_USER		VARCHAR(255)		NULL
);

COMMENT ON COLUMN TB_PROC_LOG.PROC_NM IS '프로시저명';
COMMENT ON COLUMN TB_PROC_LOG.EXEC_START_DATE IS '프로시저 시작시간';
COMMENT ON COLUMN TB_PROC_LOG.EXEC_PARAM IS '프로시저 파라메터';
COMMENT ON COLUMN TB_PROC_LOG.RESULT_MSG IS '결과 메세지';
COMMENT ON COLUMN TB_PROC_LOG.EXEC_USER IS '작업자';
